[package]
name = "overlayfs-purge"
version = "0.2.0"
edition = "2021"
authors = ["Adrian Friedli <adrian.friedli@husqvarnagroup.com>"]
description = "Filesystem overlay cleaner for system upgrades"
homepage = "https://www.gardena.com/"
license = "MIT"

[dependencies]
globset = "0.4"
nix = "0.13"
thiserror = "1.0"
xattr = "0.2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
