[package]
name = "overlayfs-purge"
version = "0.1.0"
authors = ["Adrian Friedli <adrian.friedli@husqvarnagroup.com>"]
description = "Filesystem overlay cleaner for system upgrades"
homepage = "https://www.gardena.com/"
license = "MIT"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
globset = "0.4"
nix = "0.13"
xattr = "0.2"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
