#!/bin/sh
# SPDX-License-Identifier: MIT OR Apache-2.0

# List current devices on the gateway
# Use -i to list only included devices

# Supports files generated by Shadoway and lemonbeatd.

SHADOWAY_DIR=/var/lib/lemonbeatd

print_info() {
    echo "[$NUMBER]"
    echo "Name: $NAME"
    echo "Address: $IPV6"
    echo "Wakeup channel: $WAKEUP_CHANNEL"
    echo "Included: $INCLUDED"
    echo "SGTIN: $SGTIN"
    echo "HW version: $HW_VER"
    echo "Bootloader version: $BOOT_VER"
    echo "Stack version: $STACK_VER"
    echo "Application version: $APP_VER"
    echo
    NUMBER=$((NUMBER + 1))
}

NUMBER=1

for device in "$SHADOWAY_DIR"/Device_* ; do
    DEVICE_FILE="$(cat "$device"/*.json | sed -En "s/([a-z_]+\")\ *:/\1 :/p")"
    NAME="$(echo "$DEVICE_FILE" | awk '/name/ {$1=$2=""; print $0}' | awk -F '"' '{print $2}')"
    HW_VER="$(echo "$DEVICE_FILE" | awk '/version_hw/ {print $3}' | cut -d '"' -f2)"
    BOOT_VER="$(echo "$DEVICE_FILE" | awk '/version_boot/ {print $3}' | cut -d '"' -f2)"
    STACK_VER="$(echo "$DEVICE_FILE" | awk '/version_stack/ {print $3}' | cut -d '"' -f2)"
    APP_VER="$(echo "$DEVICE_FILE" | awk '/version_app/ {print $3}' | cut -d '"' -f2)"
    IPV6="$(echo "$DEVICE_FILE" | awk '/address/ {print $3}' | cut -d '"' -f2)"
    SGTIN="$(echo "$DEVICE_FILE" | awk '/serialid/ {print $3}' | cut -d '"' -f2)"
    INCLUDED="$(echo "$DEVICE_FILE" | awk '/included/ {print $3}' | tr -d ,)"
    WAKEUP_CHANNEL="$(echo "$DEVICE_FILE" | awk '/wakeup_channel/ {print $3}' | tr -d ,)"

    if [ "$1" = "-i" ]; then
        if [ "$INCLUDED" = "true" ]; then
            print_info
        fi
    else
        print_info
    fi

done
