#!/bin/sh
#
# Check if IPR initialization has been done & run if needed.

set -ue

ipr_setup_done="$(fw_printenv -n ipr_setup_done 2>/dev/null || echo 0)"
if [ "${ipr_setup_done}" = "1" ]; then
    echo "IPR setup already done. Skipping." >&2
    exit 0
fi

# Note: the following two dependencies are intentionally here, rather
# than in the service file as Requires= and After=. The reason for
# this is that ipr.service is part of the boot process, even if the
# file /etc/ipr_setup_done exists. systemd awaits dependencies first
# and checks ConditionPathExists= after that (which is the expected
# behaviour). This would block the boot process when no Internet is
# present (first boot at customer or after factory reset and no
# Ethernet connected).
/lib/systemd/systemd-networkd-wait-online -i eth0
/lib/systemd/systemd-time-wait-sync

# Note: not checking for return value as we have set -e above;
# ipr-tool.py and shell will already each print an error message.

/usr/bin/ipr-tool --init-gateway
/usr/bin/ipr-tool --verify-ipr-data
fw_setenv ipr_setup_done 1
