#!/bin/sh
#
# Check if IPR initialization has been done & run if needed.

set -ue

ipr_setup_done="$(fw_printenv -n ipr_setup_done 2>/dev/null || echo 0)"
if [ "${ipr_setup_done}" = "1" ]; then
    # quit because the IPR setup is already done
    exit 0
fi

# note: not checking for return value as we have set -e above;
# ipr-tool.py and shell will already each print an error message.

/usr/bin/ipr-tool --init-gateway
/usr/bin/ipr-tool --verify-ipr-data
fw_setenv ipr_setup_done 1
