#!/bin/sh
#
# Run the selftest script in case it has never been run (successfully)
# before but the ipr setup did.
# This is expected to happen exactly once during manufacturing.

set -u

exit_error()
{
    message=$1

    fct-tool --set-leds red
    echo "$message" >&2
    exit 1
}

self_test_passed="$(fw_printenv -n self_test_passed 2>/dev/null || echo 0)"
if [ "${self_test_passed}" = "1" ]; then
    # set LEDs to green if we're still in manufacturing
    if [ ! -f /etc/fct_finalized ]; then
        /usr/bin/fct-tool --set-leds green
    fi
    # Quit because the selftest has already been passed in the past.
    exit 0
fi

gatewayid="$(fw_printenv -n gatewayid 2>/dev/null)"
if [ $? -ne 0 ]; then
    exit_error "U-Boot variable gatewayid not set - can not run selftest!"
fi

selftest --ipr-id "${gatewayid}"
if [ $? -ne 0 ]; then
    exit_error "Selftest failed!"
fi

fw_setenv self_test_passed 1

fct-tool --set-leds green
