#!/bin/sh
#
# Run the selftest script in case it has never been run (successfully)
# before but the ipr setup did.
# This is expected to happen exactly once during manufacturing.

set -u

exit_error()
{
    message=$1

    # We print a helpful error message to stderr and exit with a non-zero code.
    # This causes the calling service unit to invoke the error handler. The
    # error handler will then upload the results to the manufacturing server
    # and turn all LEDs red.
    echo "$message" >&2
    exit 1
}

self_test_passed="$(fw_printenv -n self_test_passed 2>/dev/null || echo 0)"
if [ "${self_test_passed}" = "1" ]; then
    # set LEDs to green if we're still in manufacturing and before FCT
    # (i.e. rerun of bootstrapping process)
    if [ ! -f /etc/fct_finalized ]; then
        /usr/bin/fct-tool --set-leds green
    fi
    echo "Selftest has already been passed. Skipping." >&2
    exit 0
fi

gatewayid="$(fw_printenv -n gatewayid 2>/dev/null)"
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
    exit_error "U-Boot variable gatewayid not set - can not run selftest!"
fi

selftest --ipr-id "${gatewayid}"
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
    exit_error "Selftest failed!"
fi

# As soon as the LEDs are green, the gateway can be removed from power during
# manufacturing. This will likely happen faster than the 30 seconds configured
# in /proc/sys/vm/dirty_expire_centisecs. Calling sync ensures our data to be
# save once the LEDs turn green.
sync

fw_setenv self_test_passed 1

fct-tool --set-leds green
