#!/bin/sh
#
# Run the selftest script in case it has never been run (successfully)
# before but the ipr setup did.
# This is expected to happen exactly once during manufacturing.

set -u

self_test_passed="$(fw_printenv -n self_test_passed 2>/dev/null || echo 0)"
if [ "${self_test_passed}" = "1" ]; then
    # Quit because the selftest has already been passed in the past.
    exit 0
fi

gatewayid="$(fw_printenv -n gatewayid 2>/dev/null)"
if [ $? -ne 0 ]; then
    echo "U-Boot variable gatewayid not set - can not run selftest!" >&2
    exit 1
fi

selftest --ipr-id "${gatewayid}"
if [ $? -ne 0 ]; then
    echo "Selftest failed!" >&2
    exit 1
fi

fw_setenv self_test_passed 1

# Set LED #1 (WiFi) green
echo 1 > /sys/class/gpio/gpio27/value
# Set LED #3 (Power) green
echo 1 > /sys/class/gpio/gpio19/value
